language: ruby
bundler_args: --without development
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
env:
  global:
    secure: | # CODECLIMATE_REPO_TOKEN
      dZRm2M5OZt5BZsyDAbOCiHmXrO7a9su9dPpV3zL4pPjRgMILcBaijUv4BmC
      +7u/B/y4UTGDQA1AvaPhol8/lGY4zxlFsEwqwRVJONEUlxbb/FRFOB74TrY
      RSYBKrBARb8/Xi+TF6VIcqH2d/K4dPEwa6lUX8tpUK3aX61ALKRs4=
